### ISSUE TITLE
No data folder for assignment 2

### ISSUE THREAD

**Issue by Flurry58** [rhodyprog4ds/BrownFall24#1]
In assignment 2 in section 2.4.4 it says: 
There are two files in the data folder, both can be read in with read_csv but need some options or fixing.

    try to read in the german.data file, what happens with the default settings? What option do you need to use to make it look right?

    try to read in the .csv file that’s included in the template repository, use the error messages you get to try to fix the file manually (any text editor, including jupyter can edit a .csv), making notes about what changes you made in a markdown cell.

Where is this data folder? It is not in my portfolio or anywhere on the website, thank you.

From Logan Pollack

**Comment by brownsarahm** [comment]
[in the instructions it says how to get that](https://rhodyprog4ds.github.io/BrownFall24/assignments/02-python-access.html#:~:text=after%20you%20finish/revise/get%20feedback%20on%20a1%2C%20get%20template%20files%20by%20syncing%20your%20portfolio)
