### ISSUE TITLE
Assigment 7 and reading files 

### ISSUE THREAD

**Issue by efsa95** [rhodyprog4ds/BrownFall24#8]
In the example of iris you read the files with
iris_df = sns.load_dataset('iris')
Looking at UCI download of iris it has 4 files:
bezdekiris.data 
Index
iris.data
iris.names

How did you load these into a data frame? Trying on my own I get very different rows/cols.  All the datasets on UCI have a similar format. How do I actually load these into data frames?

**Comment by brownsarahm** [comment]
so I used the seaborn loader for iris, since we used it in class y ou would need a different dataset for assignments. 

the `.data` file is the data and `.names` has the column names. YOu would read in the data file and manually specify the headers
